### ISSUE TITLE
FB9157626 - Preload Top Hit breaks run_at document_start

### ISSUE THREAD

**Issue by lapcat** [lapcat/SafariExtensions#1]
If a Safari web extension injected content script has `"run_at": "document_start"` specified in the extension's `manifest.json`, the script can fail to run at document start when Safari's "Preload Top Hit" setting is enabled. This bug occurs on both iOS and macOS.

A bug report has been filed with Apple as FB9157626

More details and a sample project are in my blog post: https://lapcatsoftware.com/articles/2021-6-11.html

**Comment by xeenon** [comment]
This is fixed in WebKit Web Extensions and Safari Technology Preview 192.

**Comment by lapcat** [comment]
This appears to be fixed in Safari 18.
