### ISSUE TITLE
FB10033446 (Fixed?) - Safari web extensions keep getting unregistered by launch services

### ISSUE THREAD

**Issue by lapcat** [lapcat/SafariExtensions#2]
I believe that this issue only affects Safari web extensions, not Safari app extensions, because my Safari app extension is older and has a much larger user base, but I've only received reports about this issue from users of my new Safari web extension.

The bug is that web extensions installed from the Mac App Store do not appear in Safari Preferences. This can happen on initial install, or it can happen at some point later. When the bug occurs, all of the user's installed web extensions disappear from Safari Preferences. If your Mac app calls `SFSafariApplication showPreferencesForExtensionWithIdentifier`, you get `SFErrorDomain error 1`, which is `SFErrorNoExtensionFound`.

I've discovered a reliable workaround. Run this command in Terminal:

`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f -R /Applications/Safari.app`

Curiously, running the same command on the Safari extension container app does not work; you have to run it on Safari itself.

Clearly this is some kind of bug with the Launch Services database.

**Comment by lapcat** [comment]
Apple's Response:

> Resolution:Potential fix identified - In macOS 13

**Comment by xeenon** [comment]
Yes, should be fixed.
