### ISSUE TITLE
FB11501135 - Permissions area blank in Safari 16 Extensions Preferences on Big Sur

### ISSUE THREAD

**Issue by lapcat** [lapcat/SafariExtensions#23]
1. Open Safari 16.0 (16614.1.25.9.10) on macOS 11.7 (20G817) 
2. Open Preferences window 
3. Select Extensions pane 
4. Select an extension

Expected results: The extension permissions are displayed in the lower right box.

Actual results: The lower right box is empty. See attached screenshot.

This bug does not affect macOS Monterey, only Big Sur.

![Screen Shot 2022-09-12 at 1 48 58 PM](https://user-images.githubusercontent.com/56086/209581755-7b965abd-99ae-461e-9fb3-6897bdf041f9.png)

**Comment by lapcat** [comment]
Apple's response:

> Resolution:Investigation complete - Unable to diagnose with current information

**Comment by xeenon** [comment]
This was fixed with a code change in Safari.
