### ISSUE TITLE
FB10033445 - run_at document_start is unreliable on macOS

### ISSUE THREAD

**Issue by lapcat** [lapcat/SafariExtensions#3]
This bug is related to https://github.com/lapcat/SafariExtensions/issues/1 but occurs on macOS even when "Preload Top Hit" is disabled. In my initial testing, I can't reproduce the bug on iOS with "Preload Top Hit" disabled, so perhaps the iOS implementation is a little different.

More details and a sample project are in my blog post: https://lapcatsoftware.com/articles/web-extension-bug.html

**Comment by xeenon** [comment]
This is fixed in WebKit Web Extensions and Safari Technology Preview 192.

**Comment by lapcat** [comment]
This appears to be fixed in Safari 18.
