### ISSUE TITLE
FB7641240 - Safari extension alert needs link to support document

### ISSUE THREAD

**Issue by lapcat** [lapcat/SafariExtensions#33]
In Safari Technology Preview Release 103 (Safari 13.2, WebKit 14610.1.7.3.2) there's a new alert that appears when the user enables an extension, as shown in the attached screenshot "STP Alert". This alert needs a link to an Apple support document on the web with more information, because it's difficult for users to make this decision based on only the information in the alert. 
![STP Alert](https://user-images.githubusercontent.com/56086/209602202-4ad3a411-4fbb-492b-8c75-cbf0b046f4f4.jpg)

There should probably also be a link to the support document in the Extensions Preferences window too, as shown in the attached screenshot "STP Extensions".
![STP Extensions](https://user-images.githubusercontent.com/56086/209602212-9f3c6d51-885f-4359-b7c6-56df92b58d04.jpg)

**Comment by lapcat** [comment]
Apple's response:

> Resolution:Potential fix identified - In macOS 11

I'm not sure what Apple means. I don't see a fix.

**Comment by xeenon** [comment]
A link was added to the "an app or service interfering with clicking" dialog.

This "are you sure" dialog on enable is no longer in Safari 17, since app extensions now have the same permission model of web extensions.
