### ISSUE TITLE
FB9174301 - Add Content Blocker extensions to Safari's new Extension sheet

### ISSUE THREAD

**Issue by deanPGM** [lapcat/SafariExtensions#7]
In Safari on iOS/iPadOS 15 beta 1, there is a new extensions popover which lets you manage currently installed extensions to be on/off.

It would be great if this sheet also included Content Blocker extensions also. As you can see from the attached screenshots, I have a few content blocker extensions installed on my device which show in the settings app, but do not show in the new Safari extensions popover.

**Comment by xeenon** [comment]
This was done sometime in the last release or two.
